title: "Plant Photographer — TryHackMe"
description: "Professional penetration testing documentation for the Plant Photographer room."
theme: jekyll-theme-primer

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - docs
